name: Build artifact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_packages:
    runs-on: ubuntu-latest

    steps:

    - name: Pull repo
      uses: actions/checkout@v2
            
    - name: Cache build files
      uses: actions/cache@v2
      with:
        path: | 
          ~/.ivy2/cache
          ~/.sbt
        key: sbt-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
              ${{ runner.os }}-maven-
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run build
      run: sbt clean test dist
      env:
        UPDATE_DB: ${{ secrets.UPDATE_DB }}
        APP_USER_SECRET: ${{ secrets.APP_USER_SECRET }}
        DB_LOCATION_USER: ${{ secrets.DB_LOCATION_USER }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    - name: Move build
      run: mv /home/runner/work/app-sync-users-ms/app-sync-users-ms/target/universal/app-sync-users-ms-0.1.zip  ~/app-sync-users-ms-latest.zip

    - name: Uploading build
      uses: actions/upload-artifact@v2
      with:
        name: app-sync-users-ms-latest.zip
        path: ~/app-sync-users-ms-latest.zip

  build_image:
    needs: build_packages
    runs-on: ubuntu-latest

    steps:

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app-sync-users-ms-latest.zip

      - name: Uzip packages
        uses: montudor/action-zip@v0.1.1
        with:
          args: unzip -qq app-sync-users-ms-latest.zip -d app-sync-users-ms-latest-dir

      - name: Pull repo
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Move build
        run: mv /home/runner/work/app-sync-users-ms/app-sync-users-ms/Dockefile  Dockefile

      - name: List of files
        run: ls -lh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: user/app:latest