name: Docker Image CI

on:
  workflow_run:
    workflows: ["build-scala"]
    branches: [master]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: app-sync-users-ms-latest.zip
