name: Docker Image CI

on:
  workflow_run:
    workflows: ["Build artifact"]
    branches: [master]
    types: 
      - completed
      - requested

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: app-sync-users-ms-latest.zip
